# Generated by Django 5.2.5 on 2026-01-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
    ]
