# Generated by Django 5.2.5 on 2026-01-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_student_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
